name: Only memdisk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependancies
      run: sudo apt install uuid-dev nasm perl genisoimage mtools netpbm
    - name: make
      run: make -j$(nproc) memdisk 
    - name: Find memdisk file
      run: find memdisk
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: memdisk/memdisk
        retention-days: 30
        if-no-files-found: warn  # Do not fail if files are missing
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.9
          
