name: AutoBuild II

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependancies
      run: sudo apt install uuid-dev nasm perl genisoimage mtools netpbm
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
