name: AutoBuild II

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependancies
      run: sudo apt install uuid-dev nasm perl genisoimage mtools netpbm
    - name: make
      run: make
        - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
            memdisk/memdisk
            version.mk 
            mbr/*.bin 
            core/pxelinux.0 
            core/lpxelinux.0
            core/isolinux.bin
            core/isolinux-debug.bin 
            dos/syslinux.com 
            win32/syslinux.exe
            win64/syslinux64.exe 
            dosutil/*.com 
            dosutil/*.sys 
            memdisk/memdisk 
            com32/menu/*.c32 
            com32/modules/*.c32 
            com32/mboot/*.c32 
            com32/hdt/*.c32 
            com32/rosh/*.c32 
            com32/gfxboot/*.c32 
            com32/sysdump/*.c32 
            com32/lua/src/*.c32 
            com32/chain/*.c32 
            com32/lib/*.c32 
            com32/libutil/*.c32 
            com32/gpllib/*.c32 
            com32/elflink/ldlinux/*.c32 
            com32/cmenu/libmenu/*.c32  
            utils/gethostip 
            utils/isohybrid 
            utils/mkdiskimage 
            mtools/syslinux 
            linux/syslinux 
            extlinux/extlinux
        retention-days: 30  # Keep artifacts for 30 days
